### ISSUE TITLE
[Console spam] Task #69 for InfoBoardReloaded v1.6.2

### ISSUE THREAD

**Issue by MrSkoper** [pixar02/InfoboardReloaded#9]
Help me.
Log

> `[Server thread/WARN]: [InfoBoardReloaded] Task #69 for InfoBoardReloaded v1.6.2 generated an exception
org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67) ~[spigot.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:248) ~[spigot.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:58) ~[spigot.jar:git-Spigot-5695bca-53fccdf]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:448) ~[spigot.jar:git-Spigot-5695bca-53fccdf]
	at com.sk89q.util.yaml.YAMLProcessor.load(YAMLProcessor.java:111) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldConfiguration.loadConfiguration(WorldConfiguration.java:336) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldConfiguration.<init>(WorldConfiguration.java:212) ~[?:?]
	at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:230) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(WorldGuardPlugin.java:1016) ~[?:?]
	at com.pixar02.infoboard.APIS.WorldGuard.getRegionsIn(WorldGuard.java:41) ~[?:?]
	at com.pixar02.infoboard.APIS.WorldGuard.boardsAllowedHere(WorldGuard.java:25) ~[?:?]
	at com.pixar02.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:62) ~[?:?]
	at com.pixar02.infoboard.Timers$2.run(Timers.java:81) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-5695bca-53fccdf]
	at java.lang.Thread.run(Unknown Source) [?:?]
[14:44:40] `

**Comment by MrSkoper** [comment]
I solved the problem, she was at WorldGuard
